#!/usr/bin/env python3
import random
import subprocess
import os

if os.name == 'nt':
    subprocess.run('cls', shell=True)
elif os.name == 'posix':
    subprocess.run('clear')
else:
    print("Unknown OS, so not clearing screen.")

possible_chars = [

    '`', '~', '1', '!', '2', '@', '3', '#', '4', '$', '5', '%', '6', '^', '7', '&', '8', '*', '9', '(', '0', ')', '-', '_', '=', '+',


    'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'
    'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l',
    'z', 'x', 'c', 'v', 'b', 'n', 'm',


    'Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P',
    'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L'
    'Z', 'X', 'C', 'V', 'B', 'N', 'M',


    '[', '{', ']', '}', '', '|', ';', ':', "'", '"', ',', '<', '.', '>', '/', '?'
]
while True:
 try:
    length = int(input("What is the desired length of your password? \n <<< "))
    break
 except ValueError:
     print("Choose it as a number. (eg, 5 instead of five.)")

passwordunjoined = random.sample(possible_chars, k=length)
password = "".join(passwordunjoined)
print(f"Password: {password} ")





